### ISSUE TITLE
Add tests for new methods

### ISSUE THREAD

**Issue by tomharmon** [Isaaclbj/CS4500-A1P2#15]
Hi, sorry for the # of issues, but could you please add tests for the new methods in the api?

I believe the following are missing:
1. `get`
2. `set`
3. `index_of`
4. `hash/hash_me`

**Comment by Isaaclbj** [comment]
No worries, I will add more tests asap

**Comment by jessica-cheng** [comment]
Could you include a remove method and add test for this too?

**Comment by tomharmon** [comment]
@jessica-cheng I made a new issue for the remove method, you should make separate issues for unrelated items by the way

**Comment by Isaaclbj** [comment]
done
