### ISSUE TITLE
Including string.h and standardizing string.h and object.h

### ISSUE THREAD

**Issue by jessica-cheng** [Isaaclbj/CS4500-A1P2#17]
Could you please use the object and string classes from these Piazza posts and have your test reflect these new definitions
https://piazza.com/class/k51bluky59n2jr?cid=345
https://piazza.com/class/k51bluky59n2jr?cid=330

**Comment by jessica-cheng** [comment]
Or maybe Jan Vitek's APIs
https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by Isaaclbj** [comment]
done
