### ISSUE TITLE
Get rid of implementation

### ISSUE THREAD

**Issue by jessica-cheng** [Isaaclbj/CS4500-A1P2#19]
Hi I see you've done the changes like we've asked but remember to leave out the implementation and fields. They should just be method stubs...

**Comment by Isaaclbj** [comment]
im not sure what you mean. please tell me where is the implementation you want me to remove. thanks

**Comment by jessica-cheng** [comment]
I believe my partner has created a pull request for object.h. Please take a look and do the same for string.h. Basically, as said on the assignment and piazza post [@317](https://piazza.com/class/k51bluky59n2jr?cid=317), these APIs you are providing us should not include implementation, only method stubs. We are the ones who should be working of from your design and implementing your APIs.

**Comment by jessica-cheng** [comment]
Also, please include tests for your test-array.cpp file as we also need to use your tests to test our implementations. Thanks!
