### ISSUE TITLE
Consistent Object and String

### ISSUE THREAD

**Issue by tomharmon** [Isaaclbj/CS4500-A1P2#20]
Hey,

I saw you adapted the object/string that Vitek had made a while back in class. However there's some issues with Vitek's implementation discussed [here
](https://piazza.com/class/k51bluky59n2jr?cid=248) and even Vitek mentioned it was a bad idea for the hash_me function. It also conflicts with some of my dependencies.

Someone else posted on [piazza](https://piazza.com/class/k51bluky59n2jr?cid=345
) a repo for an object/string that solves that issue, would you mind adapting that standard instead?

**Comment by Isaaclbj** [comment]
Done.
