### ISSUE TITLE
Remove `insert`, `has`

### ISSUE THREAD

**Issue by tomharmon** [Isaaclbj/CS4500-A1P2#25]
Can you remove these methods please? I didn't see anyone else who requested them so it ends up as more work for implementers and also you would need to add tests for those methods since they're not yet tested in `test-array.cpp`

**Comment by Isaaclbj** [comment]
Although our team received an API with those two methows, I totally argee that we don't need them (and they are painful to implement). So, I have removed them from my code. Enjoy!
